### ISSUE TITLE
Error when use `Model.aggregate`: Mongoose 5.x disallows passing a spread of operators to `Model.aggregate()`. Instead of `Model.aggregate({ $match }, { $skip })`, do `Model.aggregate([{ $match }, { $skip }])`

### ISSUE THREAD

**Issue by wxs77577** [craftup/node-mongo-tenant#62]
MongooseError: Mongoose 5.x disallows passing a spread of operators to `Model.aggregate()`. Instead of `Model.aggregate({ $match }, { $skip })`, do `Model.aggregate([{ $match }, { $skip }])`
    at Function.aggregate (/Users/johnny/projects/work/tenant-test/node_modules/mongoose/lib/model.js:3921:11)
    at Function.aggregate (/Users/johnny/projects/work/tenant-test/node_modules/mongo-tenant/index.js:295:32)
    at file:///Users/johnny/projects/work/tenant-test/index.js:31:49
    at Layer.handle [as handle_request] (/Users/johnny/projects/work/tenant-test/node_modules/router/lib/layer.js:102:15)
    at next (/Users/johnny/projects/work/tenant-test/node_modules/router/lib/route.js:144:13)
    at Route.dispatch (/Users/johnny/projects/work/tenant-test/node_modules/router/lib/route.js:109:3)
    at handle (/Users/johnny/projects/work/tenant-test/node_modules/router/index.js:515:11)
    at Layer.handle [as handle_request] (/Users/johnny/projects/work/tenant-test/node_modules/router/lib/layer.js:102:15)
    at /Users/johnny/projects/work/tenant-test/node_modules/router/index.js:291:22
    at Function.process_params (/Users/johnny/projects/work/tenant-test/node_modules/router/index.js:349:12)
    at next (/Users/johnny/projects/work/tenant-test/node_modules/router/index.js:285:10)
    at file:///Users/johnny/projects/work/tenant-test/index.js:22:3
    at Layer.handle [as handle_request] (/Users/johnny/projects/work/tenant-test/node_modules/router/lib/layer.js:102:15)
    at trim_prefix (/Users/johnny/projects/work/tenant-test/node_modules/router/index.js:330:13)
    at /Users/johnny/projects/work/tenant-test/node_modules/router/index.js:294:7
    at Function.process_params (/Users/johnny/projects/work/tenant-test/node_modules/router/index.js:349:12)

**Comment by redgumnfp** [comment]
As far as I can see, the below (line 295 of index.js):
return super.aggregate.apply(this, operations);

Needs to be:
return super.aggregate.apply(this, [operations]);
